-- Инициализация таблиц

-- заглушки
CREATE TABLE IF NOT EXISTS "user"
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS event
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);


-- Создание таблицы подборок
CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN      NOT NULL,
    title  VARCHAR(255) NOT NULL
);

-- Промежуточная таблица для связи Many-to-Many (Event <-> Compilation)
CREATE TABLE IF NOT EXISTS event_compilation
(
    event_id       BIGINT NOT NULL,
    compilation_id BIGINT NOT NULL,

    -- Составной первичный ключ предотвращает дублирование связей
    PRIMARY KEY (event_id, compilation_id),

    -- Внешние ключи
    CONSTRAINT fk_event_compilation_event
        FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_compilation_compilation
        FOREIGN KEY (compilation_id) REFERENCES compilation (id) ON DELETE CASCADE
);

-- Создание таблицы заявок на участие
CREATE TABLE IF NOT EXISTS request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     BIGINT                      NOT NULL,
    requester_id BIGINT                      NOT NULL,
    status       VARCHAR(50)                 NOT NULL,

    -- Внешние ключи
    CONSTRAINT fk_request_event FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_request_user FOREIGN KEY (requester_id) REFERENCES "user" (id)
);